### ISSUE TITLE
Is it possible to make a button the position of the player?

### ISSUE THREAD

**Issue by giacesaro** [giustini/react-soccer-lineup#11]
Hi I wanted to ask if you could make the player's position as a button, so that you can be clickable and can select a player from a list.

**Comment by giustini** [comment]
Hi @giacesaro! Thanks for your comment and sorry for the delay.

I think what you need is a callback that is triggered when the user clicks on a player, and I just added support for `onClick` events on players.

I encourage you to review the 0.4.0 version of the library and try this change 🙂 You can also see this new feature on the demo page: https://rsl-example.netlify.app/ (there is a checkbox to make clickable the players of every team)

Cheers!
